#load("@protobuf//bazel:proto_library.bzl", "proto_library")
#load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_proto_library")
#
#proto_library(
#    name = "ac_compressor_status_change_proto",
#    srcs = ["ac_compressor_status_change_proto.proto"],
#    visibility = ["//visibility:public"],
#)
#
#cpp_proto_library(
#    name = "ac_compressor_status_change_proto_cc",
#    protos = ["ac_compressor_status_change_proto.proto"],
#    visibility = ["//visibility:public"],
#)

# some toolchain issues, so no protos for now...
