cc_library(
    name = "ac_compressor_status_change",
    srcs = ["ac_compressor_status_change.cpp"],
    hdrs = ["ac_compressor_status_change.h"],
    deps = ["//proto:ac_compressor_status_change_proto_cc"],
)
